version: "2"
services: 
  db: 
    environment: 
      MYSQL_DATABASE: ussd
      MYSQL_PASSWORD: ussd
      MYSQL_ROOT_PASSWORD: rosianah
      MYSQL_USER: ussd
    build: "./database/"
    restart: always

  ussd: 
    build: "."
    command: "/usr/bin/hhvm -m server -p 8080"
    depends_on: 
      - db
    environment: 
      AT_API_KEY: b5c3fb350dcfe8a5e90f97d6f12c08793aaff1d61f0a5128fed37373af6107d9
      AT_USER_NAME: Rosianah
      USSD_DB_HOST: "db:3306"
      USSD_DB_PASSWORD: ussd
      USSD_DB_USER: ussd
    ports: 
      - "8080:8080"
    restart: always


